"""fixed num_vists to num_visits

Revision ID: 22fce0e4140c
Revises: 36108cd05115
Create Date: 2019-12-22 21:51:19.013255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22fce0e4140c'
down_revision = '36108cd05115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('associations', sa.Column('num_visits', sa.Integer(), nullable=True))
    op.drop_column('associations', 'num_vists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('associations', sa.Column('num_vists', sa.INTEGER(), nullable=True))
    op.drop_column('associations', 'num_visits')
    # ### end Alembic commands ###
