"""new user-to-user relatinship table

Revision ID: 38f62d72def4
Revises: a73bbcae87e7
Create Date: 2019-12-22 20:05:01.810856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f62d72def4'
down_revision = 'a73bbcae87e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship_identifier',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.UniqueConstraint('user_id', 'friend_id', name='unique_friendships')
    )
    op.drop_table('user_user_identifier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_user_identifier',
    sa.Column('user0_id', sa.INTEGER(), nullable=True),
    sa.Column('user1_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user0_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user1_id'], ['users.user_id'], )
    )
    op.drop_table('friendship_identifier')
    # ### end Alembic commands ###
