"""added img_src, address, and num_visits to destinations table

Revision ID: 3a150fb4d7a7
Revises: 38f62d72def4
Create Date: 2019-12-22 21:12:09.800639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a150fb4d7a7'
down_revision = '38f62d72def4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('destinations', sa.Column('img_src', sa.String(length=1000), nullable=True))
    op.add_column('destinations', sa.Column('num_visits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'num_visits')
    op.drop_column('destinations', 'img_src')
    op.drop_column('destinations', 'address')
    # ### end Alembic commands ###
