"""user-to-user relatinship table

Revision ID: a73bbcae87e7
Revises: bec1930c6d8f
Create Date: 2019-12-22 19:54:07.622939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73bbcae87e7'
down_revision = 'bec1930c6d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_user_identifier',
    sa.Column('user0_id', sa.Integer(), nullable=True),
    sa.Column('user1_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user0_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user1_id'], ['users.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_user_identifier')
    # ### end Alembic commands ###
