"""added username to users, yelp_link and region to destinations


Revision ID: a97509e996f7
Revises: 22fce0e4140c
Create Date: 2019-12-24 08:31:46.817199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97509e996f7'
down_revision = '22fce0e4140c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('region', sa.String(length=50), nullable=True))
    op.add_column('destinations', sa.Column('yelp_link', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index('ix_users_name', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('destinations', 'yelp_link')
    op.drop_column('destinations', 'region')
    # ### end Alembic commands ###
