"""empty message

Revision ID: e82054010216
Revises: 3ef2e3c6f98c
Create Date: 2020-01-18 16:57:14.825836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e82054010216'
down_revision = '3ef2e3c6f98c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('region', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_region'), 'users', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_region'), table_name='users')
    op.drop_column('users', 'region')
    # ### end Alembic commands ###
